Some common terms to remember
1. Corpus
2. Vocabulary
3. Document
4. Word

<h1>Bag Of Words</h1>

In [1]:
import numpy as np
import pandas as pd

In [6]:
import pandas as pd

df = pd.DataFrame({
    "text": ["people watch ngocson",
             "ngocson watch thuytien",
             "people write comment",
             "hello Thuy Tien",  # Added a comma here
             "Hello Ngoc Son"],
    "output": [1, 1, 0, 1, 1]  # This list should now match the length of "text"
})

print(df)

                     text  output
0    people watch ngocson       1
1  ngocson watch thuytien       1
2    people write comment       0
3         hello Thuy Tien       1
4          Hello Ngoc Son       1


In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [8]:
bow = cv.fit_transform(df['text'])

In [9]:
print(cv.vocabulary_)

{'people': 4, 'watch': 9, 'ngocson': 3, 'thuytien': 7, 'write': 10, 'comment': 0, 'hello': 1, 'thuy': 6, 'tien': 8, 'ngoc': 2, 'son': 5}


In [10]:
bow.toarray()

array([[0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0]])

In [12]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())


[[0 0 0 1 1 0 0 0 0 1 0]]
[[0 0 0 1 0 0 0 1 0 1 0]]
[[1 0 0 0 1 0 0 0 0 0 1]]


In [13]:
cv.transform(['Ngoc Son watch Thuy Tien']).toarray()

array([[0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0]])

In [15]:
X = bow.toarray()
y = df['output']

In [16]:
y

0    1
1    1
2    0
3    1
4    1
Name: output, dtype: int64

<h1>N-Grams</h1>

In [17]:
df = pd.DataFrame({"text": ["People watch Ngoc Son",
                            "Ngoc Son watch Ngoc Son",
                            "Thuy tien watch Ngoc Son",
                            "Ngoc Son watch Thuy Tien",
                            "Hello Ngoc Son Thuy Tien"], "output":[1, 1, 0, 0, 0]})

df

text  output
0     People watch Ngoc Son       1
1   Ngoc Son watch Ngoc Son       1
2  Thuy tien watch Ngoc Son       0
3  Ngoc Son watch Thuy Tien       0
4  Hello Ngoc Son Thuy Tien       0

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2, 2))

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'people watch': 2, 'watch ngoc': 7, 'ngoc son': 1, 'son watch': 4, 'thuy tien': 5, 'tien watch': 6, 'watch thuy': 8, 'hello ngoc': 0, 'son thuy': 3}


In [22]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 0 1 0]]
[[0 2 0 0 1 0 0 1 0]]


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3, 3))

In [24]:
bow = cv.fit_transform(df['text'])

In [25]:
print(cv.vocabulary_)

{'people watch ngoc': 3, 'watch ngoc son': 9, 'ngoc son watch': 2, 'son watch ngoc': 5, 'thuy tien watch': 7, 'tien watch ngoc': 8, 'son watch thuy': 6, 'watch thuy tien': 10, 'hello ngoc son': 0, 'ngoc son thuy': 1, 'son thuy tien': 4}


<h1>TF-IDF(Term frequency-Inverse document frequency)</h1>

In [26]:
df = pd.DataFrame({"text": ["People watch Ngoc Son",
                            "Ngoc Son watch Ngoc Son",
                            "Thuy tien watch Ngoc Son",
                            "Ngoc Son watch Thuy Tien",
                            "Hello Ngoc Son Thuy Tien"], "output":[1, 1, 0, 0, 0]})

df

text  output
0     People watch Ngoc Son       1
1   Ngoc Son watch Ngoc Son       1
2  Thuy tien watch Ngoc Son       0
3  Ngoc Son watch Thuy Tien       0
4  Hello Ngoc Son Thuy Tien       0

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

arr = tfid.fit_transform(df['text']).toarray()

In [28]:
arr

array([[0.        , 0.35801021, 0.75132464, 0.35801021, 0.        ,
        0.        , 0.42328319],
       [0.        , 0.6524015 , 0.        , 0.6524015 , 0.        ,
        0.        , 0.38567418],
       [0.        , 0.36889198, 0.        , 0.36889198, 0.51846481,
        0.51846481, 0.43614894],
       [0.        , 0.36889198, 0.        , 0.36889198, 0.51846481,
        0.51846481, 0.43614894],
       [0.65216961, 0.31076232, 0.        , 0.31076232, 0.43676559,
        0.43676559, 0.        ]])

In [29]:
print(tfid.idf_)

[2.09861229 1.         2.09861229 1.         1.40546511 1.40546511
 1.18232156]
